version: '3'
services:
  airflow-worker-3:
    image: apache/airflow:2.5.1
    tmpfs:
      - /opt/airflow/
    command: celery worker
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@<MAIN-NODE-PRIVATE-IP>:5432/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@<MAIN-NODE-PRIVATE-IP>:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@<MAIN-NODE-PRIVATE-IP>:6379/0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - 8793:8793
    restart: unless-stopped
