version: '3.8'

services:
  ansible-sync:
    build:
      context: .  
      dockerfile: Dockerfile  
    volumes:
      - /home/azureuser/airflow/dags/:/ansible/sync  # Maps the dags directory in the host to the container directory where the repo is synced.
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False  # Disables host key checking for Ansible.
    entrypoint: >
      sh -c "while true; do
      ansible-playbook -i inventory sync_git.yml;
      sleep 30;
      done"
    # Runs the `sync_git.yml` playbook every 30 seconds to sync the repository.
